mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
)

mysite/polls/urls.py

from django.conf.urls import patterns,url
from polls import views
from django.contrib.auth.decorators import login_required
urlpatterns=patterns('',
					url(r'^$',login_required(views.IndexView.as_view()),name='index'),
					url(r'^(?P<pk>\d+)/$',login_required(views.DetailView.as_view()),name='detail'),
					url(r'^(?P<pk>\d+)/results/$',login_required(views.ResultsView.as_view()),name='results'),
					url(r'^(?P<question_id>\d+)/vote/$',views.vote,name='vote'),
					url(r'^signup/$', views.call_signup, name='call_signup'),
					url(r'^login/$', views.call_login, name='call_login'),
					url(r'^createuser/$', views.create_user, name='create_user'),
					url(r'^verifyuser/$', views.verify_user, name='verify_user'),
					url(r'^changepassword/$', views.call_changepassword, name='call_changepassword'),
					url(r'^savepassword/$', views.save_password, name='save_password'),
					url(r'^logout/$', views.log_out, name='log_out'),
)
                

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):              
        return self.question_text
	
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
	was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
		
class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __unicode__(self):              
        return self.choice_text

mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render,get_object_or_404
from django.core.urlresolvers import reverse
from django.views import generic
from polls.models import Question,Choice
from django.utils import timezone
from django.contrib.auth import authenticate,login,logout
from mysite import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.context_processors import csrf



class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
	
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
		
@login_required
def vote(request,question_id):
	p=get_object_or_404(Question,pk=question_id)
	try:
		selected_choice=p.choice_set.get(pk=request.POST['choice'])
	except(KeyError,Choice.DoesNotExist):
		return render(request,'polls/detail.html/',{'question':p,'message':"You didn't select a choice."})
	else:
		selected_choice.votes+=1
		selected_choice.save()
	return HttpResponseRedirect(reverse('polls:results',args=(p.id,)))
	
def call_signup(request):
	return render(request,'polls/signup.html/')
	
def create_user(request):
	username=request.POST.get('username')
	firstname=request.POST.get('firstname')
	lastname=request.POST.get('lastname')
	email=request.POST.get('email')
	password=request.POST.get('password')
	user=User.objects.create_user(username, email, password)
	user.first_name=firstname
	user.last_name=lastname
	user.save()
	return HttpResponseRedirect(reverse('polls:index'))
	
def call_login(request):
	return render(request,'polls/login.html/')
def verify_user(request):
	username= request.POST.get('username')
	password=request.POST.get('password')
	user = authenticate(username=username, password=password)
	if user is not None:
		if user.is_active:
			login(request,user)
			return HttpResponseRedirect(reverse('polls:index'))

		else:
			return render(request,'polls/login.html/',{'message':'The account has been disabled.'})
	else:
		return render(request,'polls/login.html/',{'message':'The username-password combination is incorrect.'})
@login_required
def call_changepassword(request):
	return render(request,'polls/changepwd.html/')
@login_required
def save_password(request):
	user=request.user
	username=request.user.username
	oldpassword=request.POST.get('oldpassword')
	password1=request.POST.get('password1')
	password2=request.POST.get('password2')
	test_user= authenticate(username=username, password=oldpassword)
	if test_user is None:
		return render(request,'polls/changepwd.html/',{'message':'The existing password is incorrect.'})
	else:
		if password1!=password2:
			return render(request,'polls/changepwd.html/',{'message':'The entered passwords did not match.'})
		else:
			if password1:
				user.set_password(password1)
				user.save()
				return render(request,'polls/login.html/',{'message':'The password has been successfully changed.'})
			else:
				return render(request,'polls/changepwd.html/',{'message':'Null passwords not accepted.'})

def log_out(request):
	logout(request)
	return HttpResponseRedirect(reverse('polls:call_login'))

mysite/polls/templates/polls/changepwd.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
    <!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
    <!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
    <!--[if IE 9]> <html class="no-js ie9 oldie" lang="en"> <![endif]-->
    <meta charset="utf-8">
    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="Coming soon, Bootstrap, Bootstrap 3.0, Free Coming Soon, free coming soon, free template, coming soon template, Html template, html template, html5, Code lab, codelab, codelab coming soon template, bootstrap coming soon template">
    <title>POLLS-Password-Change</title>
    <!-- ============ Google fonts ============ -->
    <link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet'
        type='text/css' />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700,300,800'
        rel='stylesheet' type='text/css' />
	
    <!-- ============ Add custom CSS here ============ -->
    <link href="{% static 'polls/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
      <link href="{% static 'polls/css/changepwd.css' %}" rel="stylesheet" type="text/css" />    
   
    <link href="{% static 'polls/css/font-awesome.css' %}" rel="stylesheet" type="text/css" />

</head>
<body>
    <div id="custom-bootstrap-menu" class="navbar navbar-default " role="navigation">
    <div class="container">
	<img src="{{STATIC_URL}}polls/img/111.png" class="imgh pointer">
        <div style="text-align:center;" class="navbar-header"><a class="navbar-brand" href="#">POLL IT</a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
        </div>
     
    </div>
</div>
      
        <div class="container">
           <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
           <div id="banner">
             <h1> <strong></strong> </h1>
 <div class="images">
    <img src="{{STATIC_URL}}polls/img/42.png" class="img2">
	 <img src="{{STATIC_URL}}polls/img/12.png" class="img1" style="width:430px;">
   
    </div>
            <h5><strong></strong></h5>
           
           </div>
          
              
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="registrationform">
            <form class="form-horizontal" action="{%url 'polls:save_password'%}"method="post">
			{% csrf_token %}
                <fieldset>
                    <legend>Change Your Password <i class="fa fa-pencil pull-right"></i></legend>
                           

					<div class="form-group">
                        <label for="password" class="col-lg-2 control-label">
                            Current Password</label>
                        <div class="col-lg-10">
                            <input type="password" class="form-control" id="password" name="oldpassword" placeholder="Username">
                        </div>
                    </div>
					
                    <div class="form-group">
                        <label for="password" class="col-lg-2 control-label">
                            New Password</label>
                        <div class="col-lg-10">
                            <input type="password" class="form-control" id="password" name="password1" placeholder="Password">
                          
                        </div>
                    </div>
					
					 <div class="form-group">
                        <label for="password" class="col-lg-2 control-label">
                            Re-Enter Password</label>
                        <div class="col-lg-10">
                            <input type="password" class="form-control" id="password" name="password2" placeholder="Password">
                          
                        </div>
                    </div>
                    
                     
                           
                       
                    <div class="form-group">
                        <div class="col-lg-10 col-lg-offset-2">
                            <button type="reset" class="btn btn-warning help">
                                Help</button>
                            <button type="submit" class="btn btn-primary">
                                Save Changes</button>
                        </div>
                    </div>
                </fieldset>
            </form>
         </div>



         </div>
        </div>
         {% if message %}<p><h3><font color="white">  {{message}}</font></h3></p>
{% endif %}
        <script src="{% static 'polls/js/jquery.js' %}" type="text/javascript"></script>
        <script src="{% static 'polls/js/bootstrap.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'polls/js/jquery.backstretch.js' %}" type="text/javascript"></script>
        <script type="text/javascript">
            'use strict';

            /* ========================== */
            /* ::::::: Backstrech ::::::: */
            /* ========================== */
            // You may also attach Backstretch to a block-level element
            $.backstretch(
        [
           "{{STATIC_URL}}polls/img/124.jpg",
            "{{STATIC_URL}}polls/img/02.jpg",
            "{{STATIC_URL}}polls/img/24.jpg",
            "{{STATIC_URL}}polls/img/14.jpg"
        ],

        {
            duration: 4500,
            fade: 1500
        }
    );
        </script>

</body>
</html>

mysite/polls/templates/polls/detail.html


{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
    <!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
    <!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
    <!--[if IE 9]> <html class="no-js ie9 oldie" lang="en"> <![endif]-->
    <meta charset="utf-8">
    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="Coming soon, Bootstrap, Bootstrap 3.0, Free Coming Soon, free coming soon, free template, coming soon template, Html template, html template, html5, Code lab, codelab, codelab coming soon template, bootstrap coming soon template">
    <title>POLLs-INDEX</title>
    <!-- ============ Google fonts ============ -->
    <link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet'
        type='text/css' />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700,300,800'
        rel='stylesheet' type='text/css' />
    <!-- ============ Add custom CSS here ============ -->
   <link href="{% static 'polls/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
      <link href="{% static 'polls/css/login.css' %}" rel="stylesheet" type="text/css" />    
   
    <link href="{% static 'polls/css/font-awesome.css' %}" rel="stylesheet" type="text/css" />

</head>
<body>
    <div id="custom-bootstrap-menu" class="navbar navbar-default " role="navigation">
    <div class="container">
	<img src="{{STATIC_URL}}polls/img/111.png" class="imgh pointer">
	<div style="text-align:center;" class="navbar-header"><a class="navbar-brand" href="#">POLL IT</a>
        
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse navbar-menubuilder">
            <ul class="nav navbar-nav navbar-right">
                
            <div class="logout">
                <form class="form-horizontal" action="{%url 'polls:log_out'%}" method="post">
             {% csrf_token %}
                  <button type="submit" class="btn btn-primary">
                                Logout</button>
								</form></div>
	             <div class="logout">

                <form class="form-horizontal" action="{%url 'polls:call_changepassword'%}" method="post">
             {% csrf_token %}
                  <button type="submit" class="btn btn-primary">
                                Change Password</button>
								</form></div>
            </ul>
        </div>
    </div>
</div>

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" class="btn btn-primary"  />
</form>
  

	
	
      
 <script src="{% static 'polls/js/jquery.js' %}" type="text/javascript"></script>
        <script src="{% static 'polls/js/bootstrap.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'polls/js/jquery.backstretch.js' %}" type="text/javascript"></script>
        <script type="text/javascript">
            'use strict';

            /* ========================== */
            /* ::::::: Backstrech ::::::: */
            /* ========================== */
            // You may also attach Backstretch to a block-level element
            $.backstretch(
        [
            "{{STATIC_URL}}polls/img/124.jpg",
            "{{STATIC_URL}}polls/img/02.jpg",
            "{{STATIC_URL}}polls/img/24.jpg",
            "{{STATIC_URL}}polls/img/14.jpg"
        ],

        {
            duration: 4500,
            fade: 1500
        }
    );
        </script>
		
		<div class="footer">
	<p>&copy 2016 IMG</p>
	</div>

</body>
</html>

mysite/polls/templates/polls/index.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
    <!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
    <!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
    <!--[if IE 9]> <html class="no-js ie9 oldie" lang="en"> <![endif]-->
    <meta charset="utf-8">
    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="Coming soon, Bootstrap, Bootstrap 3.0, Free Coming Soon, free coming soon, free template, coming soon template, Html template, html template, html5, Code lab, codelab, codelab coming soon template, bootstrap coming soon template">
    <title>POLLs-INDEX</title>
    <!-- ============ Google fonts ============ -->
    <link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet'
        type='text/css' />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700,300,800'
        rel='stylesheet' type='text/css' />
    <!-- ============ Add custom CSS here ============ -->
   <link href="{% static 'polls/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
      <link href="{% static 'polls/css/login.css' %}" rel="stylesheet" type="text/css" />    
   
    <link href="{% static 'polls/css/font-awesome.css' %}" rel="stylesheet" type="text/css" />

</head>
<body>
    <div id="custom-bootstrap-menu" class="navbar navbar-default " role="navigation">
    <div class="container">
	<img src="{{STATIC_URL}}polls/img/111.png" class="imgh pointer">
	<div style="text-align:center;" class="navbar-header"><a class="navbar-brand" href="#">POLL IT</a>
        
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse navbar-menubuilder">
            <ul class="nav navbar-nav navbar-right">
                
            <div class="logout">
                <form class="form-horizontal" action="{%url 'polls:log_out'%}" method="post">
             {% csrf_token %}
                  <button type="submit" class="btn btn-primary">
                                Logout</button>
								</form></div>
	     <div class="logout">

                <form class="form-horizontal" action="{%url 'polls:call_changepassword'%}" method="post">
             {% csrf_token %}
                  <button type="submit" class="btn btn-primary">
                                Change Password</button>
								</form></div>
            </ul>
        </div>
    </div>
</div>

<div class="container">
           <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
           <div id="banner">
             <h1> <strong></strong> </h1>
  {% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}" />


{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
            <h5><strong></strong></h5>
           
           </div>
          
              
            </div>
  

	
	
      
 <script src="{% static 'polls/js/jquery.js' %}" type="text/javascript"></script>
        <script src="{% static 'polls/js/bootstrap.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'polls/js/jquery.backstretch.js' %}" type="text/javascript"></script>
        <script type="text/javascript">
            'use strict';

            /* ========================== */
            /* ::::::: Backstrech ::::::: */
            /* ========================== */
            // You may also attach Backstretch to a block-level element
            $.backstretch(
        [
            "{{STATIC_URL}}polls/img/124.jpg",
            "{{STATIC_URL}}polls/img/02.jpg",
            "{{STATIC_URL}}polls/img/24.jpg",
            "{{STATIC_URL}}polls/img/14.jpg"
        ],

        {
            duration: 4500,
            fade: 1500
        }
    );
        </script>
		
		<div class="footer">
	<p>&copy 2016 IMG</p>
	</div>

</body>
</html>

mysite/polls/templates/polls/results.html





{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
    <!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
    <!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
    <!--[if IE 9]> <html class="no-js ie9 oldie" lang="en"> <![endif]-->
    <meta charset="utf-8">
    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="Coming soon, Bootstrap, Bootstrap 3.0, Free Coming Soon, free coming soon, free template, coming soon template, Html template, html template, html5, Code lab, codelab, codelab coming soon template, bootstrap coming soon template">
    <title>POLLs-INDEX</title>
    <!-- ============ Google fonts ============ -->
    <link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet'
        type='text/css' />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700,300,800'
        rel='stylesheet' type='text/css' />
    <!-- ============ Add custom CSS here ============ -->
   <link href="{% static 'polls/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
      <link href="{% static 'polls/css/login.css' %}" rel="stylesheet" type="text/css" />    
   
    <link href="{% static 'polls/css/font-awesome.css' %}" rel="stylesheet" type="text/css" />

</head>
<body>
    <div id="custom-bootstrap-menu" class="navbar navbar-default " role="navigation">
    <div class="container">
	<img src="{{STATIC_URL}}polls/img/111.png" class="imgh pointer">
	<div style="text-align:center;" class="navbar-header"><a class="navbar-brand" href="#">POLL IT</a>
        
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse navbar-menubuilder">
            <ul class="nav navbar-nav navbar-right">
                
            <div class="logout">
                <form class="form-horizontal" action="{%url 'polls:log_out'%}" method="post">
             {% csrf_token %}
                  <button type="submit" class="btn btn-primary">
                                Logout</button>
								</form></div>
	
	      <div class="logout">

                <form class="form-horizontal" action="{%url 'polls:call_changepassword'%}" method="post">
             {% csrf_token %}
                  <button type="submit" class="btn btn-primary">
                                Change Password</button>
								</form></div>
            </ul>
        </div>
    </div>
</div>

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

	
	
      
 <script src="{% static 'polls/js/jquery.js' %}" type="text/javascript"></script>
        <script src="{% static 'polls/js/bootstrap.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'polls/js/jquery.backstretch.js' %}" type="text/javascript"></script>
        <script type="text/javascript">
            'use strict';

            /* ========================== */
            /* ::::::: Backstrech ::::::: */
            /* ========================== */
            // You may also attach Backstretch to a block-level element
            $.backstretch(
        [
            "{{STATIC_URL}}polls/img/124.jpg",
            "{{STATIC_URL}}polls/img/02.jpg",
            "{{STATIC_URL}}polls/img/24.jpg",
            "{{STATIC_URL}}polls/img/14.jpg"
        ],

        {
            duration: 4500,
            fade: 1500
        }
    );
        </script>
		
		<div class="footer">
	<p>&copy 2016 IMG</p>
	</div>

</body>
</html>